name: CI-CD

on:
  push:
    branches:
      - producao

jobs:
  build-js-css:
    name: Build JS CSS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - run: npm install
      - run: npm run production

      - name: Commit assets
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHun Action"
          git checkout -B deploy
          git add -f public/
          git commit -m "Build front-end assets"
          git push -f origin deploy

      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          script: 'cd gudezamusic && sh server_deploy.sh'


  # remove-branch:
  #   name: remove deploy branch
  #   runs-on: ubuntu-latest
  #   needs: [build-js]
  #   if: github.ref == 'refs/head/production'
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         token: ${{ secrets.PUSH_TOKEN }}

  #     - name: Reset
  #       run: git push origin --delete deploy
