on:
  push:
    branches:
      - producao
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
          uses: actions/checkout@v2
      - name: Copy .env
          run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
          run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
          run: php artisan key:generate
      - name: Directory Permissions
          run: chmod -R 777 storage
      - name: Directory Permissions ugo+rw
          run: chmod -R ugo+rw storage
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
